server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.24.46.5:3306/guli_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Wujibing@123456
  redis:
    host: 39.105.92.39
    timeout: 10000

  rabbitmq:
    host: 175.24.46.5
    username: jsjs
    password: jsjs
    virtual-host: /jsonwu

mybatis-plus:
  mapper-locations: classpath:mapper/wms/*.xml  #mapper映射文件获取
  global-config:
    db-config:
      id-type: auto #默认使用数据库只增
  ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 30000




